Bug 77982 stale auth header after reload
eShopWorld/captain-hook pull request #207
Opened 2020-08-20 12:42 UTC by nikhilgirraj

**What**
Issue - Bug 77982: Reload on Authentication changes does not work
1. Added unit test to replicate the bug. 
2. Added `HasConfigChanged` method to `IAuthenticationHandler` interface
3. *Adding a check for `HasConfigChanged` in `AuthenticationHandlerFactory`

**Why draft PR**
1. Should I keep these changes or implement an IEqualityComparer?
2. Thoughts on extending the unit tests for OIDC auth handler as well?

2020-08-20 13:30 UTC, mszymeshop commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/BasicAuthenticationHandler.cs
> +            if (newConfig?.Type == this.BasicAuthenticationConfig.Type && newConfig is BasicAuthenticationConfig authConfig)
Is the Type property check necessary? The object type should be enough.

2020-08-20 13:30 UTC, mszymeshop commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +            if (newConfig is OidcAuthenticationConfig oidcNewConfig)
You are not checking the type here so whatever is decided I think this should be consistent with BasicAuthenticationConfig.

2020-08-20 13:33 UTC, mszymeshop commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +                               && oidcNewConfig.Scopes.Length == OidcAuthenticationConfig.Scopes.Length
Use of `SequenceEqual` might be clearer here.

2020-08-20 13:36 UTC, mszymeshop commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +        [MemberData(nameof(AuthenticationChangeTestData))]
At the moment this test does not constitute a theory, do you plan on extending it? You have only a single test case here.

2020-08-20 13:37 UTC, mszymeshop commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +                Assert.NotEqual(token, lastToken);
As long as it does its job I am thinking that this test is hard to reason about when a failure happens. If it happens for the second token you will not know that.

What I would suggest you do is create all 4 tokens and put in an array. Then compare that array with the expected array of tokens. Benefits: clear identification which element in the array is incorrect. Also you get to do a single assert for an entire test.

2020-08-20 14:07 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +        [MemberData(nameof(AuthenticationChangeTestData))]
Yes, I was trying to add another set of tests in there. I'll remove it since the OIDC requires a much different flow. Working on it at the moment.

2020-08-20 14:10 UTC, nikhilgirraj commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/BasicAuthenticationHandler.cs
> +            if (newConfig?.Type == this.BasicAuthenticationConfig.Type && newConfig is BasicAuthenticationConfig authConfig)
The type check indeed isn't necessary. Removing it.

2020-08-20 14:12 UTC, nikhilgirraj commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +            if (newConfig is OidcAuthenticationConfig oidcNewConfig)
yep.

2020-08-20 16:24 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +                Assert.NotEqual(token, lastToken);
Makes sense. Please have a look at final changes.

2020-08-20 16:26 UTC, nikhilgirraj commented
Also, do I create a real PR instead of draft? Or is this one okay to merge?

2020-08-20 22:38 UTC, tabman83 requested changes

2020-08-20 22:38 UTC, tabman83 commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +        {
Please use this convention for test names:
`When_StateUnderTest_Expect_ExpectedBehavior`
as it's the one we aim to spread across the codebase

2020-08-21 08:37 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +        {
Changing.

2020-08-21 08:38 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +        {
Changed.

2020-08-21 08:50 UTC, tabman83 commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
The bigbrother mock is something you can declare at the beginning and reuse across all of your tests, just to make them more readable. See example from other test classes.

2020-08-21 08:52 UTC, tabman83 commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +        public async Task AuthenticationHandler_Returns_RespectiveHandlerForConfigType(WebhookConfig config, IAuthenticationHandler expectedHandler)
AuthenticationHandlerFactory_WhenInvoked_ReturnsCorrectType

2020-08-24 08:31 UTC, chomick commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/AuthenticationHandlerFactory.cs
> +                        _handlers.TryRemove(key, out _);
I don't think you need `TryRemove` as you are certain the element exists and you are in critical section

2020-08-24 08:35 UTC, tabman83 requested changes

2020-08-24 08:35 UTC, tabman83 commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +            if (newConfig is OidcAuthenticationConfig oidcNewConfig)
Reopening as I don't think you need the order by

2020-08-24 09:04 UTC, mszymeshop commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +            receivedTokens.Should().Equal(expectedTokens);
What I meant is Fluent Assertions documentation. Checked now and Equals verifies the ordering, so closing here.

2020-08-24 09:06 UTC, mszymeshop commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +            _bigBrother = Mock.Of<BigBrother>();
I think you want to go with IBigBrother here instead (although this seems to work, we should be mocking the types your system under tests relies on, and this is IBigBrother here).

2020-08-24 09:09 UTC, mszymeshop commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +                expectedTokens.Add($"Bearer {expectedAccessToken}");
I don't see this change for some reason.

2020-08-24 09:16 UTC, dawidkeshop commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +        public async Task When_OidcAuthParamsUpdated_ExpectUpdatedTokenInRequests()
Maybe I'm missing something, but couldn't we just have a `Theory` here and use `GetOidcAuthChangeTestData` as `MemberData`?
I think it's easier to follow and fix if we have multiple separate test cases instead of one big test with couple of loops inside.

2020-08-24 09:54 UTC, nikhilgirraj commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +            if (newConfig is OidcAuthenticationConfig oidcNewConfig)
I added order by for situations where scopes in the two configurations are specified as 
config1 -> { "scope1", "scope2" }
config2 -> { "scope2", "scope1" }

Here config1 should match config2.

2020-08-24 09:55 UTC, nikhilgirraj commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/AuthenticationHandlerFactory.cs
> +                        _handlers.TryRemove(key, out _);
I'm happy to change this but seems like it would internally do the same. Or would it not?

2020-08-24 09:55 UTC, chomick commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +            if (newConfig is OidcAuthenticationConfig oidcNewConfig)
It is not necessary but it will work properly - it just allows code to ignore change in the same scopes order - this is NULL change from auth point of view - so, code is correct but it also would be fine if we refreshed (unnecessarily) config for this case. (makes the code simpler).

2020-08-24 09:56 UTC, nikhilgirraj commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/AuthenticationHandlerFactory.cs
> +                        _handlers.TryRemove(key, out _);
I'm happy to change this but seems like it would internally do the same since it is an extension method. Or would it not?

2020-08-24 09:58 UTC, chomick approved these changes
Few outstanding questions from guys but overall looks good

2020-08-24 10:00 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +            _bigBrother = Mock.Of<BigBrother>();
Right, I'll change it.

2020-08-24 10:05 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +        public async Task When_OidcAuthParamsUpdated_ExpectUpdatedTokenInRequests()
The loop tests whether changes to AuthenticationConfig reflect in GetTokenAsync. Making it MemberData would reset the test context for every run which is not what I wanted?

Unless you meant to put various combinations of these into different tests. Did you?

2020-08-24 10:46 UTC, nikhilgirraj commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +            if (newConfig is OidcAuthenticationConfig oidcNewConfig)
In that case, I can remove it.

2020-08-24 11:05 UTC, nikhilgirraj commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/AuthenticationHandlerFactory.cs
> +                        _handlers.TryRemove(key, out _);
I'm happy to change this but seems like it would internally do the same since a `.Remove` is an extension method. Or would it not?

2020-08-25 08:28 UTC, nikhilgirraj commented
As per @mszymeshop's suggestions, 
- I have changed the tests from "check-for-a-different-handler-for-a-different-auth-config" instead of "check-for-a-different-token-for-a-different-auth-config". 
- Removed the public static method in Basic Auth handler.

2020-08-25 08:47 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +            handlers.Should().OnlyHaveUniqueItems();
Checks for reference since `.Equals` is not overridden. Let me know if there's a better way.

2020-08-25 09:20 UTC, mszymeshop commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +                SetupMockHttpResponse(mockHttp, webhookConfig.AuthenticationConfig as OidcAuthenticationConfig, expectedAccessToken);
Now that you don't have the expected token being used, is this still required?

2020-08-25 09:21 UTC, mszymeshop commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +            handlers.Should().OnlyHaveUniqueItems();
ok, as long as you have tested that.

2020-08-25 11:46 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +                SetupMockHttpResponse(mockHttp, webhookConfig.AuthenticationConfig as OidcAuthenticationConfig, expectedAccessToken);
Good point. Since now I'm only testing the handlers, this should be fine.

2020-08-25 13:14 UTC, mszymeshop commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +                if (oidcNewConfig.Scopes != null)
I think you might have overcomplicated that. A use of `??` and `?.` would be sufficient here, unless I am not seeing something.

2020-08-25 13:26 UTC, mszymeshop approved these changes

2020-08-25 15:16 UTC, nikhilgirraj commented on src/CaptainHook.EventHandlerActor/Handlers/Authentication/OidcAuthenticationHandler.cs
> +                if (oidcNewConfig.Scopes != null)
Just wanted to cover the situation where (that.Scopes?.SequenceEqual(other.Scopes) ?? false) is what I thought, but this would not cover the situation where both are null. Of course that's a hypothetical one.

2020-08-25 15:26 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Web/Authentication/AuthenticationFactoryTests.cs
> +                SetupMockHttpResponse(mockHttp, webhookConfig.AuthenticationConfig as OidcAuthenticationConfig, expectedAccessToken);
Removed it. :-)

2020-08-25 16:48 UTC, merged