#81037 Update auth mappings and validators
eShopWorld/captain-hook pull request #211
Opened 2020-08-21 22:33 UTC by tabman83

2020-08-24 08:56 UTC, dawidkeshop approved these changes
Looks OK

2020-08-24 08:56 UTC, dawidkeshop commented on src/CaptainHook.Storage.Cosmos/CaptainHook.Storage.Cosmos.csproj
> +    <PackageReference Include="Eshopworld.Data.CosmosDb" Version="3.0.3-preview3" />
Should this be a `preview` version?

2020-08-24 09:08 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/CaptainHook.Storage.Cosmos.csproj
> +    <PackageReference Include="Eshopworld.Data.CosmosDb" Version="3.0.3-preview3" />
I have updated the CosmosDb package to support custom deserialization to enable polymorphism on the auth db entities. Since the PR is still outstanding, I have released a preview version of that package in order to unblock the work here. Once te PR for the CosmosDb is approved and merged, I will updated to non-preview version here.

2020-08-24 09:19 UTC, dawidkeshop commented on src/CaptainHook.Storage.Cosmos/CaptainHook.Storage.Cosmos.csproj
> +    <PackageReference Include="Eshopworld.Data.CosmosDb" Version="3.0.3-preview3" />
OK, makes sense for me.

2020-08-24 09:34 UTC, chomick requested changes
Thanks Nino, good job getting this implementation ready.

However, this PR is way too big. You should have broken it into smaller PRs, even if they are chained one after another, if you did not have anyone to review it.

There would be many ways to break it down, but at least would focus on getting individual layers PRed.

Couple of questions to be answered. 
Also, can you confirm if you tested it locally?

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs
> +
No reason to keep adding the wrong pattern here

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +            var typeDesc = jObject["type"]?.Value<string>();
Will it work as expected if JObject does not contain 'type'? Or will it throw exception?

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +    public class AuthenticationDtoJsonConverter : JsonConverter
Do you have unit tests for this?

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Application/Validators/PolymorphicValidator.cs
> +	public class PolymorphicValidator<T, TInterface> : ChildValidatorAdaptor<T, TInterface>
Do we need this wrapper class or can we use many ChildValidatorAdaptor on your EndpointDtoValidator?
I don't know the fluent validators but maybe they support it out of the box?

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Contract/BasicAuthenticationDto.cs
> +        public const string Type = "Basic";
Are we not using field on base class?

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/Models/BasicAuthenticationSubdocument.cs
> +        [JsonProperty("type")]
Do you need to repeat the attribute here?

2020-08-24 09:34 UTC, chomick commented on src/Tests/CaptainHook.Application.Tests/Validators/Dtos/AuthenticationDtoValidatorTests.cs
> +        [ClassData(typeof(InvalidUris))]
We should also validate that url with `{abc}` will also be considered invalid in auth setup

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs
> +        private static AuthenticationEntity MapAuthentication(AuthenticationDto authenticationDto)
Do you have unit tests for the auth mappings? for any/all handlers?

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
Do you have unit tests for that?

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/AuthenticationSubdocumentJsonConverter.cs
> +    internal class AuthenticationSubdocumentJsonConverter : JsonConverter
Do you have unit tests for that?

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +namespace CaptainHook.Contract
I don't think serialiser belongs to the contract - contract is just POCOs; serialiser would be within API or Application namespace.

2020-08-24 09:34 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
What's the reason for this class?

2020-08-24 09:39 UTC, tabman83 commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +            var typeDesc = jObject["type"]?.Value<string>();
It will be null and will fall to the default case on the switch (tested)

2020-08-24 09:39 UTC, tabman83 commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +    public class AuthenticationDtoJsonConverter : JsonConverter
I don't - do we want it? Also for the cosmos json converter?

2020-08-24 09:39 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
Nope!

2020-08-24 09:42 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
I don't because this is a copy of MS implementation here: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/06b961a6c181995590097f764b296403169974f8/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs 
which is internal

2020-08-24 09:42 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/AuthenticationSubdocumentJsonConverter.cs
> +    internal class AuthenticationSubdocumentJsonConverter : JsonConverter
Nope

2020-08-24 09:42 UTC, tabman83 commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +namespace CaptainHook.Contract
I can move it to API

2020-08-24 09:45 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
I need that to specify serializer settings under which I have my custom AuthenticationSubdocumentJsonConverter

2020-08-24 09:48 UTC, tabman83 commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +namespace CaptainHook.Contract
If I move it to API or Application it would create a circular dependency as those 2 projects already depend on Contract

2020-08-24 09:56 UTC, tabman83 commented on src/CaptainHook.Application/Validators/PolymorphicValidator.cs
> +	public class PolymorphicValidator<T, TInterface> : ChildValidatorAdaptor<T, TInterface>
There's no support out of the box although the developer claims it is going to be added in v. 9.2
There's a discussion which started here https://github.com/FluentValidation/FluentValidation/issues/1237 where I borrowed this approach. ChildValidatorAdaptor is not something we can use directly.

2020-08-24 09:57 UTC, tabman83 commented on src/CaptainHook.Contract/BasicAuthenticationDto.cs
> +        public const string Type = "Basic";
Not anymore, these I need to reuse when matching the auth type in the mappers and deserializer

2020-08-24 09:58 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/Models/BasicAuthenticationSubdocument.cs
> +        [JsonProperty("type")]
I can double check if the attribute is inferred from the base class

2020-08-24 09:59 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> -                Type = AuthenticationType.OIDC,
Yes, will change.

2020-08-24 10:10 UTC, chomick commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +    public class AuthenticationDtoJsonConverter : JsonConverter
Yes, we should - otherwise, how do you know it works :)
These should be quick to add, cases I would test:
- username/password type
- oidc type
- invalid type

2020-08-24 10:12 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
Doesn't matter if internal or not :) It is code that should be tested noramlly. However, I would question why do we need that?

2020-08-24 10:13 UTC, chomick commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +namespace CaptainHook.Contract
Contract should not depend on anything.
API/App should depend on contract.

What is it in contract that we need from API/App?

2020-08-24 10:21 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
Can you use RequestOptions?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions?view=azure-dotnet

You would have to extend the cosmos db package again to allow for serialisation settings to be specified in the repository (you could expose it via repo protected property so it can be redefined in subclasses)

2020-08-24 10:24 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> -                Type = AuthenticationType.OIDC,
Yes it is!

2020-08-24 10:25 UTC, tabman83 commented
> Thanks Nino, good job getting this implementation ready.
> 
> However, this PR is way too big. You should have broken it into smaller PRs, even if they are chained one after another, if you did not have anyone to review it.
> 
> There would be many ways to break it down, but at least would focus on getting individual layers PRed.
> 
> Couple of questions to be answered.
> Also, can you confirm if you tested it locally?

Yes I tested the API locally, request is persisted to the database and on subsequent restart the new subscriber is correctly pulled from db.

2020-08-24 10:31 UTC, tabman83 commented on src/CaptainHook.Application/Handlers/Subscribers/UpsertSubscriberRequestHandler.cs
> -                MapUriTransformEntity(request.Subscriber.Webhooks.UriTransform));
It may have slipped. Re-added now.

2020-08-24 10:50 UTC, tabman83 commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +    public class AuthenticationDtoJsonConverter : JsonConverter
Added tests for this

2020-08-24 11:10 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/AuthenticationSubdocumentJsonConverter.cs
> +    internal class AuthenticationSubdocumentJsonConverter : JsonConverter
Added tests for this

2020-08-24 11:11 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/Models/BasicAuthenticationSubdocument.cs
> +        [JsonProperty("type")]
Unit tests highlighted that this can be safely removed. Done.

2020-08-24 11:13 UTC, tabman83 commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +namespace CaptainHook.Contract
The AuthenticationDtoJsonConverter is specified as an attribute on the AuthenticationDto, so if I move the AuthenticationDtoJsonConverter to a different project it would require a dependency on that project.

2020-08-24 11:14 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
That is defined in the Azure DocumentDB library, while our Cosmos package has been already upgraded to Azure Cosmos library.

2020-08-24 11:38 UTC, chomick commented on src/CaptainHook.Application/Handlers/Subscribers/UpsertSubscriberRequestHandler.cs
> -                MapUriTransformEntity(request.Subscriber.Webhooks.UriTransform));
There should be unit test that caught it

2020-08-24 11:42 UTC, chomick commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +namespace CaptainHook.Contract
Is there any other way to specify the converter than via attribute? It feels wrong that our contract needs to have the converter defined in the same project. 
I like to think of the contract almost as a auto-generated code based on some abstract contract definition :)

2020-08-24 11:43 UTC, chomick commented on src/CaptainHook.Contract/BasicAuthenticationDto.cs
> +        public const string Type = "Basic";
But the property is still part of the class - should it not be set (in ctor) to the right value?

2020-08-24 12:54 UTC, tabman83 commented on src/CaptainHook.Contract/AuthenticationDtoJsonConverter.cs
> +namespace CaptainHook.Contract
The AuthenticationDtoJsonConverter has been moved to the API project

2020-08-24 14:06 UTC, tabman83 commented on src/Tests/CaptainHook.Application.Tests/Validators/Dtos/AuthenticationDtoValidatorTests.cs
> +        [ClassData(typeof(InvalidUris))]
Added test for that

2020-08-24 14:41 UTC, tabman83 commented on src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs
> +
Will be handled in https://dev.azure.com/eshopworld/evo-core/_workitems/edit/81792

2020-08-24 14:41 UTC, tabman83 commented on src/CaptainHook.Application/Handlers/Subscribers/UpsertWebhookRequestHandler.cs
> +        private static AuthenticationEntity MapAuthentication(AuthenticationDto authenticationDto)
Will be handled in https://dev.azure.com/eshopworld/evo-core/_workitems/edit/81792

2020-08-24 14:44 UTC, tabman83 commented on src/CaptainHook.Contract/BasicAuthenticationDto.cs
> +        public const string Type = "Basic";
Right, changed that.

2020-08-26 09:23 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
As discussed, Nino will try to serialise directly in the repository using the custom converter rather than substitute the serializer for Cosmos SDK.

2020-08-26 09:23 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/JsonCosmosSerializer.cs
> +    internal class JsonCosmosSerializer : CosmosSerializer
As discussed, Nino will try to serialise directly in the repository using the custom converter rather than substitute the serializer for Cosmos SDK.

2020-08-26 09:24 UTC, chomick reviewed
Looks good with the exception for the serializer - once you manage to replace that code with repository serialisation, we should be good.

2020-08-26 11:13 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs
> +            return (SubscriberDocument)JsonConvert.DeserializeObject(
I think there should be generic version of that method as well?

2020-08-26 11:18 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs
> +            return (SubscriberDocument)JsonConvert.DeserializeObject(
I think I made a comment on particular commit - I think there should be generic version of that method, no need for Type to be used then.

2020-08-26 11:19 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/Models/WebhookSubdocument.cs
> -        [JsonProperty("uriTransform", NullValueHandling = NullValueHandling.Ignore)]
Any reason we are changing the name of the field in DB?

2020-08-26 11:21 UTC, chomick commented on src/CaptainHook.Storage.Cosmos/Models/OidcAuthenticationSubdocument.cs
> -        [JsonProperty("clientId")]
I actually likes the fact that the contract is well defined here. Right now, we will rely on the fact that some options are set somewhere and if they change, the DB doc contract will also change.
No action needed, just something to consider in future.

2020-08-26 11:24 UTC, chomick approved these changes
We MUST avoid such massive PRs - very difficult to read/reason about it - I had difficulty reviewing it and possibly I missed things

2020-08-26 12:24 UTC, merged

2020-08-26 12:24 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs
> +            return (SubscriberDocument)JsonConvert.DeserializeObject(
Changed

2020-08-26 12:25 UTC, tabman83 commented on src/CaptainHook.Storage.Cosmos/SubscriberRepository.cs
> +            return (SubscriberDocument)JsonConvert.DeserializeObject(
Changed