#81052 Remove payload logging for SAND and PROD envs
eShopWorld/captain-hook pull request #212
Opened 2020-08-24 08:04 UTC by tabman83

- SandBox should not have message payload logging to Application Insights contained within FailureWebhookEvents
- Production should not have message payload logging to Application Insights contained within FailureWebhookEvents
- Additionally, the FailureWebHook event has been renamed to FailureWebhookEvent to make it consistent with the WebhookEvent (indicating success)

2020-08-24 08:48 UTC, chomick commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
> +            var canLogPayload = (EswDevOpsSdk.GetEnvironment() != DeploymentEnvironment.Prod && EswDevOpsSdk.GetEnvironment() != DeploymentEnvironment.Sand);
I would prefer to have a feature flag rather than hardcoded envs.

2020-08-24 09:00 UTC, mszymeshop requested changes
The rename of `FailedWebHookEvent` which you have mentioned in the description is not visible in the PR.

2020-08-24 09:00 UTC, mszymeshop commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
>                  _bigBrother.Publish(new FailedWebHookEvent(
Could you add a unit test that verifies this? Somebody could change that in the future by mistake and we could end up logging these by mistake.

2020-08-26 09:08 UTC, tabman83 commented on src/CaptainHook.Common/Telemetry/FailedWebHookEvent.cs
> +        // sent for all environments except for SAND and PROD
Done!

2020-08-26 09:08 UTC, tabman83 commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
> +            var canLogPayload = (EswDevOpsSdk.GetEnvironment() != DeploymentEnvironment.Prod && EswDevOpsSdk.GetEnvironment() != DeploymentEnvironment.Sand);
Done!

2020-08-26 09:10 UTC, tabman83 commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
>                  _bigBrother.Publish(new FailedWebHookEvent(
This is now controlled by feature flags

2020-08-26 09:10 UTC, tabman83 commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
> +            var canLogPayload = (EswDevOpsSdk.GetEnvironment() != DeploymentEnvironment.Prod && EswDevOpsSdk.GetEnvironment() != DeploymentEnvironment.Sand);
Done

2020-08-26 09:10 UTC, tabman83 commented
> The rename of `FailedWebHookEvent` which you have mentioned in the description is not visible in the PR.

Not sure why it did not get through in the first place, I have re-added now.

2020-08-26 09:13 UTC, mszymeshop commented on src/CaptainHook.Common/Configuration/TempConfigLoader.cs
> +                AddEntry (client, "CaptainHook--FeatureFlags--DisablePayloadLoggingForPROD"),
Is there a reason you use 2 flags per environment? Instead of having a single one which just controls the payload? It would then be set to false for CI-PREP and true SAND-PROD?

2020-08-26 09:14 UTC, tabman83 commented on src/CaptainHook.Common/Configuration/TempConfigLoader.cs
> +                AddEntry (client, "CaptainHook--FeatureFlags--DisablePayloadLoggingForPROD"),
I have re-used a FeatureFlagsConfiguration class which is already there and it uses boolean flags

2020-08-26 09:15 UTC, tabman83 commented on src/CaptainHook.Common/Telemetry/FailedWebHookEvent.cs
> +        // sent for all environments except for SAND and PROD
Done

2020-08-26 09:15 UTC, tabman83 commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
>                  _bigBrother.Publish(new FailedWebHookEvent(
Using feature flags now

2020-08-26 09:21 UTC, mszymeshop commented on src/CaptainHook.Common/Configuration/TempConfigLoader.cs
> +                AddEntry (client, "CaptainHook--FeatureFlags--DisablePayloadLoggingForPROD"),
That is not what I am saying :) Why do you ask for SAND and PROD for each environment? Why should CI care about these entries?

2020-08-26 09:24 UTC, dawidkeshop commented on src/CaptainHook.Common/Configuration/TempConfigLoader.cs
> +                AddEntry (client, "CaptainHook--FeatureFlags--DisablePayloadLoggingForPROD"),
Couldn't we just have a single flag like `DisablePayloadLogging` which will be `false` in CI, TEST and PREP and `true` on SAND and PROD?
It looks a bit confusing to have flags with `SAND` and `PROD` in the name on every environment.

2020-08-26 09:24 UTC, dawidkeshop commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
> +            return
Do we have to check the environment type if we have a feature flag?

2020-08-26 09:27 UTC, tabman83 commented on src/CaptainHook.Common/Configuration/TempConfigLoader.cs
> +                AddEntry (client, "CaptainHook--FeatureFlags--DisablePayloadLoggingForPROD"),
Hey guys you're absolutely, right I just made a bit of confusion, let me sort this out!

2020-08-26 09:30 UTC, tabman83 commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
> +            return
I have changed that

2020-08-26 09:31 UTC, tabman83 commented on src/CaptainHook.Common/Configuration/TempConfigLoader.cs
> +                AddEntry (client, "CaptainHook--FeatureFlags--DisablePayloadLoggingForPROD"),
I have changed that

2020-08-26 09:35 UTC, chomick commented on src/CaptainHook.Common/Configuration/TempConfigLoader.cs
> +                AddEntry (client, "CaptainHook--FeatureFlags--DisablePayloadLoggingForPROD"),
Still seeing old code?

2020-08-26 09:37 UTC, tabman83 commented on src/CaptainHook.Common/Configuration/TempConfigLoader.cs
> +                AddEntry (client, "CaptainHook--FeatureFlags--DisablePayloadLoggingForPROD"),
Changed

2020-08-26 09:40 UTC, chomick approved these changes

2020-08-26 10:15 UTC, dawidkeshop approved these changes
OK, but I would do something with the name as I suggested in the comment.

2020-08-26 10:15 UTC, dawidkeshop commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
> +                var canLogPayload = !(_configurationSettings.FeatureFlags.GetFlag<DisablePayloadLoggingFeatureFlag>()?.IsEnabled ?? false);
Hmm, so the flag name is `DisablePayloadLogging`, so if `IsEnabled` is `true`, it means that feature is actually disabled, right?
Bit confusing as for me, maybe try to rename it just to `PayloadLogging` and don't have this `Disable`-`IsEnabled` construction in a single line of code?

2020-08-26 11:07 UTC, tabman83 commented on src/CaptainHook.EventHandlerActor/Handlers/RequestLogger.cs
> +                var canLogPayload = !(_configurationSettings.FeatureFlags.GetFlag<DisablePayloadLoggingFeatureFlag>()?.IsEnabled ?? false);
I know it gets confusing to read this, but we are taking from the assumption that all feature flags are disabled by default, and we don't want to disable payload logging in case the deploy goes ahead without the ff in.

2020-08-26 11:08 UTC, merged