82617 delete subscriber handler
eShopWorld/captain-hook pull request #240
Opened 2020-09-01 15:43 UTC by dawidkeshop

2020-09-01 21:21 UTC, tabman83 requested changes

2020-09-01 21:21 UTC, tabman83 commented on src/CaptainHook.Api/Controllers/EventsController.cs
> +                data => NoContent()
Can you apply the same change to DeleteWebhook

2020-09-01 21:21 UTC, tabman83 commented on src/CaptainHook.Domain/Results/OperationResult.cs
>          }
Brilliant. Functional programming all the way!

2020-09-01 21:21 UTC, tabman83 commented on src/CaptainHook.Application/Handlers/Subscribers/DeleteSubscriberRequestHandler.cs
> +        }
Is there a case where we will be returning false?
If false means deletion didn't go through then we would need a reason.

----

I personally think it does not make sense to return a boolean here as we do have OperationResult.Error to indicate a failure and describe the reason.

I would return the deleted subscriber if the operation is successful (or nothing) and an Error object from OperationResult.Error if the operation failed.

2020-09-01 21:21 UTC, tabman83 commented on src/CaptainHook.Domain/Results/OperationResult.cs
> +    }
I would probably prefer having them in a separate file otherwise it feels like they are hidden

2020-09-02 08:15 UTC, dawidkeshop commented on src/CaptainHook.Api/Controllers/EventsController.cs
> +                data => NoContent()
But why? The initial plan was to return subscriber data from every endpoint, so an API consumer can immediately see his  changes. We did this for all upserts and for delete webhook andpoint.
Here we have no longer subscriber to return, so we can't return it, so only here we must return NoContent.

2020-09-02 09:14 UTC, tabman83 commented on src/CaptainHook.Api/Controllers/EventsController.cs
> +                data => NoContent()
I understand yes

2020-09-02 09:29 UTC, dawidkeshop commented on src/CaptainHook.Application/Handlers/Subscribers/DeleteSubscriberRequestHandler.cs
> +        }
I've used `bool` just because I can't use `void` there and `false` is never returned.

Regarding returning deleted subscriber - won't it be confusing to return obsolete data?

2020-09-02 09:30 UTC, dawidkeshop commented on src/CaptainHook.Domain/Results/OperationResult.cs
>          }
Nice to read that. :)
I think if other people also like that way we can rewrite other handlers to avoid all these ` if (result.IsError) return result.Error` duplications.

2020-09-02 09:30 UTC, dawidkeshop commented on src/CaptainHook.Domain/Results/OperationResult.cs
> +    }
These are tightly coupled with `OperationResult`, but I can move it if you wish.

2020-09-02 09:44 UTC, tabman83 commented on src/CaptainHook.Domain/Results/OperationResult.cs
> +    }
May be just OperationResultExtensions in the same folder?

2020-09-02 09:44 UTC, chomick commented on src/CaptainHook.Application/Handlers/Subscribers/DeleteSubscriberRequestHandler.cs
> +        }
I would agree that returning the deleted record would be helpful/useful - you are passing just Id and if for whatever reason you deleted wrong record, you have a way to recreate it somehow and have its content/value.

2020-09-02 11:23 UTC, dawidkeshop commented on src/CaptainHook.Domain/Results/OperationResult.cs
> +    }
Actually these are `TaskExtensions`. In a separate file now.

2020-09-02 11:23 UTC, dawidkeshop commented on src/CaptainHook.Application/Handlers/Subscribers/DeleteSubscriberRequestHandler.cs
> +        }
Ok, that flow makes sense. Code changed.

2020-09-02 11:25 UTC, tabman83 commented on src/CaptainHook.Domain/Results/OperationResult.cs
> +    }
Right

2020-09-02 11:27 UTC, tabman83 approved these changes

2020-09-02 12:17 UTC, merged