Added a DeleteSubscription method to Director Service.
eShopWorld/captain-hook pull request #245
Opened 2020-09-03 09:08 UTC by nikhilgirraj

Moved ServiceBusNamespaceExtensions to CaptainHook.Common.
Added DeleteSubscription method to DirectorService (on Delete)

2020-09-03 09:16 UTC, tabman83 commented on src/CaptainHook.DirectorService/DirectorService.cs
>              return value;
@dawidkeshop  Is this correct?
I mean - Is it correct to have the delete inside this block where we also make this check (value == RefreshReaderResult.None) ?

2020-09-03 09:17 UTC, tabman83 commented on src/CaptainHook.Common/ServiceBus/ServiceBusNamespaceExtensions.cs
> +            return sbNamespace;
Why did you remove `CreateTopicIfNotExists()` ?

2020-09-03 09:30 UTC, tabman83 commented on src/CaptainHook.Common/ServiceBus/ServiceBusNamespaceExtensions.cs
> +            var sbNamespaceObj = await GetServiceBusNamespace(azureSubscriptionId, sbNamespace, cancellationToken);
I don't think you should do this all over again here.

2020-09-03 09:37 UTC, tabman83 requested changes
This build is also failing. Can you please check?

2020-09-03 10:04 UTC, dawidkeshop commented on src/CaptainHook.DirectorService/DirectorService.cs
>              return value;
Yes, because `RefreshReaderResult.None` means that there were no explicit errors during deletion and there was no creation also. 
The problem is that deletion works indefinitely and doesn't provide any actual result of the operation, it can't return Success, so we must consider None as a valid situation. It's very confusing and we have a tech debt 80123 to fix that.

2020-09-03 10:05 UTC, tabman83 commented
Suggested to move the ServiceBus manager to Common project and have it injected in Director service as well (other than Reader service) - the whole idea is to keep the SB interaction abstracted away in a common service/place.

2020-09-03 10:09 UTC, dawidkeshop commented on src/CaptainHook.DirectorService/DirectorService.cs
> +            await ServiceBusNamespaceExtensions.DeleteSubscription(_configurationSettings?.AzureSubscriptionId, _configurationSettings?.ServiceBusNamespace,
I think we don't have to use `?.` here since we are sure that `_configurationSettings` is not null.

2020-09-04 15:42 UTC, tabman83 reviewed
I have tested this locally and the EventReader does not seem to be able to read messages.
Messages sent to a newly created topic are just sitting there until they end up in DLQ.
Will try and more tests later.

As a consequence, I cannot approve this for now.

2020-09-05 16:45 UTC, tabman83 requested changes

2020-09-05 16:45 UTC, tabman83 commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +
- This method is called CreateSubscription but it does not seem to create any subscription (hence why it was not working for me locally)
- By the look of the original one this is responsible for creating both the topic and the subscription so I would call it CreateTopicAndSubscriptionAsync

2020-09-05 16:45 UTC, tabman83 commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        private async Task<ITopic> CreateTopicIfNotExists(string topicName, CancellationToken cancellationToken = default)
Please follow the convention and rename this to end in -Async

2020-09-05 16:48 UTC, tabman83 commented
Can you please have a look at the changes suggested and test it locally. Give a me a shout if you need help for running & testing it locally.

2020-09-10 08:07 UTC, nikhilgirraj commented
Manually tested readers and subscribers removal. Could not mock the calls to write unit tests for this part.

2020-09-10 09:23 UTC, chomick commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        private async Task<IServiceBusNamespace> GetServiceBusNamespaceAsync(string azureSubscriptionId, string serviceBusNamespace,
small suggestion - can you move private methods below public?

2020-09-10 09:23 UTC, chomick commented on src/CaptainHook.Common/ServiceBus/IServiceBusManager.cs
> +        Task DeleteSubscriptionAsync(string topicName, string subscriptionName, CancellationToken cancellationToken);
tiny one - maybe group the subscription related methods together in the code

2020-09-10 09:23 UTC, chomick commented on src/CaptainHook.DirectorService/DirectorService.cs
> +                await _serviceBusManager.DeleteSubscriptionAsync(readerChange.Subscriber.EventType,
What does it mean that refresh result is None? Can it be returned as success for delete operation? And in such case, should we also remove the subscription?

2020-09-10 09:23 UTC, chomick commented on src/CaptainHook.DirectorService/DirectorService.cs
> +                await _serviceBusManager.DeleteSubscriptionAsync(readerChange.Subscriber.EventType,
What will happen if the subscription is not there? Is there an exception returned? 
In such case, we should continue as the end result is as expected - subscription is gone

2020-09-10 09:23 UTC, chomick commented on src/Tests/CaptainHook.Tests/Director/DirectorServiceTests.cs
> +        public async Task DeleteReader_When_ReaderExists_Then_DeleteSubscriptionIsCalled()
What about tests for deletion failures? Can they happen?

2020-09-10 09:23 UTC, chomick commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +    public class ServiceBusManager : IServiceBusManager
We may need to exclude this code from code coverage - not sure if it is testable

2020-09-10 09:57 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        private async Task<IServiceBusNamespace> GetServiceBusNamespaceAsync(string azureSubscriptionId, string serviceBusNamespace,
aren't those already below the public ones?

2020-09-10 10:00 UTC, nikhilgirraj commented on src/CaptainHook.DirectorService/DirectorService.cs
> +                await _serviceBusManager.DeleteSubscriptionAsync(readerChange.Subscriber.EventType,
For the result None see @dawidkeshop's reply here https://github.com/eShopWorld/captain-hook/pull/245#discussion_r482862130
It only results in None afaik.

2020-09-10 10:45 UTC, nikhilgirraj commented on src/CaptainHook.DirectorService/DirectorService.cs
> +                await _serviceBusManager.DeleteSubscriptionAsync(readerChange.Subscriber.EventType,
The underlying API doesn't throw any exception in case the subscription does not exist.

2020-09-10 10:46 UTC, nikhilgirraj commented on src/Tests/CaptainHook.Tests/Director/DirectorServiceTests.cs
> +        public async Task DeleteReader_When_ReaderExists_Then_DeleteSubscriptionIsCalled()
I'm sure there can be deletion failures. If the subscriber does not exist the API spits a 404 I guess. I'll try to write tests to check the behavior of the methods though.

2020-09-10 13:54 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusNamespaceExtensions.cs
> +            var sbNamespaceObj = await GetServiceBusNamespace(azureSubscriptionId, sbNamespace, cancellationToken);
Fixed.

2020-09-10 14:23 UTC, mszymeshop requested changes

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/CaptainHook.Common.csproj
> +	  <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.34.0" />
The formatting seems to be off here.

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +    public class ServiceBusManager : IServiceBusManager
@nikhilgirraj you can use this: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=netcore-3.1

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                .WaitAndRetryForeverAsync(ExponentialBackoff);
Do we want to keep retrying forever?

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        public async Task CreateSubscriptionAsync(string subscriptionName, string topicName, bool createTopicIfNotExists, CancellationToken cancellationToken)
Do we have a usage where `createTopicIfNotExists` is `false`? By the look at usages, it is only `true` which means we probably should not support the other case at the moment.

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                await topic.Subscriptions.DeleteByNameAsync(subscriptionName + "3", cancellationToken);
What does `subscriptionName + "3"` mean?

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +            var subscription = subscriptionsList.SingleOrDefault(s => s.Name == subscriptionName.ToLowerInvariant());
Instead of going `ToLowerInvariant` use `StringComparison.OrdinalIgnoreCase` (there is invariant option available but for these entries we don't expect national characters)

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                .WithMessageLockDurationInSeconds(60)
Are there defaults available or are you copying from the previous code? I would just look out for duplications of the algorithm which might rely on similar configuration. For instance, if you say 60 seconds here and in the other place it says `use default`, this might go out of sync at some point.

To me: (a) look out for duplications (might not be applicable), (b) rely on defaults if they can be used (I am not sure what the SDK allows)

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +            return subscriptionsList.Single(t => t.Name == subscriptionName.ToLowerInvariant());
Consider StringComparison instead. Fewer temp string are created.

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                .WithDuplicateMessageDetection(TimeSpan.FromMinutes(10))
Again, is this the default or taken from the old code?

2020-09-10 14:23 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        public string GetLockToken(Message message)
If this is a public method it should probably be guarded against nulls etc.

2020-09-10 14:33 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                .WithDuplicateMessageDetection(TimeSpan.FromMinutes(10))
I can see this is old code now.

2020-09-10 14:33 UTC, mszymeshop commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                .WithMessageLockDurationInSeconds(60)
I can see this is old code.

2020-09-10 14:37 UTC, mszymeshop commented
A general suggestion, this is too big of a PR. The code you're moving and changing at the same time is represented as new code which makes it more difficult to review. Maybe this could have been divided into two PRs instead to emphasise clarity.

2020-09-10 16:47 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                .WaitAndRetryForeverAsync(ExponentialBackoff);
I'm not sure, the code was present there and I didn't question it. Seems like if we plan to try limited number of times, we would need to define the failure mechanism as well, like fail silently or throw the exception to the user?

2020-09-10 16:48 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        public async Task CreateSubscriptionAsync(string subscriptionName, string topicName, bool createTopicIfNotExists, CancellationToken cancellationToken)
It's a tricky one. Read @chomick's comment here -https://github.com/eShopWorld/captain-hook/pull/245#discussion_r486162960

2020-09-10 16:49 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                await topic.Subscriptions.DeleteByNameAsync(subscriptionName + "3", cancellationToken);
That's fixed in my latest commit, I was trying to see if I need to introduce tests for non-existing subscriptions.

2020-09-10 16:57 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                .WithDuplicateMessageDetection(TimeSpan.FromMinutes(10))
Old code.

2020-09-10 18:22 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        public string GetLockToken(Message message)
Added conditional access.

2020-09-11 11:05 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +                .WithMessageLockDurationInSeconds(60)
This is previous code. The history is lost in refactoring but I understand what you are trying to say.

2020-09-11 11:22 UTC, chomick commented on src/Tests/CaptainHook.Tests/Director/DirectorServiceTests.cs
> +        public async Task DeleteReader_When_ReaderExists_Then_DeleteSubscriptionIsCalled()
When 404 is returned, is that translated to an exception on our side or we simply swallow the error and go as nothing happened?
The error handling for service bus manager is bit unclear to me in case of deletion errors.

2020-09-11 11:23 UTC, chomick commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        public async Task CreateSubscriptionAsync(string subscriptionName, string topicName, bool createTopicIfNotExists, CancellationToken cancellationToken)
If we always plan to create topic, I would not use the param - no need if this is our normal behaviour. It was meant to be added only in case we need/want to use the service in different cases/modes and to have control over topic creation

2020-09-11 11:40 UTC, mszymeshop approved these changes

2020-09-11 19:02 UTC, tabman83 approved these changes

2020-09-11 21:32 UTC, merged