Refactor servicebus extensions
eShopWorld/captain-hook pull request #246
Opened 2020-09-03 14:04 UTC by nikhilgirraj

2020-09-03 15:26 UTC, tabman83 commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        private async Task<IServiceBusNamespace> GetServiceBusNamespace(string azureSubscriptionId, string serviceBusNamespace,
use -Async suffix

2020-09-03 15:28 UTC, tabman83 reviewed
Don't forget to inject the ServiceBusManager into the container

2020-09-03 16:13 UTC, nikhilgirraj commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        private async Task<IServiceBusNamespace> GetServiceBusNamespace(string azureSubscriptionId, string serviceBusNamespace,
done

2020-09-03 18:14 UTC, tabman83 commented on src/CaptainHook.Common/ServiceBus/ServiceBusManager.cs
> +        private int _retryCeilingSeconds = 30;
This can be a const

2020-09-03 18:15 UTC, tabman83 commented on src/CaptainHook.DirectorService/DirectorService.cs
Do we need a method just to call one line?

2020-09-03 18:16 UTC, tabman83 reviewed
Check SonarCloud for this PR
https://sonarcloud.io/project/issues?id=esw.captain-hook&pullRequest=246
to see where you can improve the quality and coverage

2020-09-03 18:19 UTC, tabman83 requested changes
@nikhilgirraj 
You still need to inject the ServiceBusManager for both the DirectorService and the EventReaderService

2020-09-04 08:30 UTC, dawidkeshop commented on src/CaptainHook.DirectorService/DirectorService.cs
> +                await DeleteSubscriptionAsync(readerChange, _cancellationToken);
Are we sure that this will be called only in case of successful scenario?

2020-09-04 08:45 UTC, nikhilgirraj commented on src/CaptainHook.DirectorService/DirectorService.cs
> +                await DeleteSubscriptionAsync(readerChange, _cancellationToken);
I am not so sure about that. Do you mean it should be called unconditionally?

2020-09-04 09:02 UTC, nikhilgirraj commented on src/CaptainHook.DirectorService/DirectorService.cs
I was assuming it would be more than a line initially. Changed.

2020-09-04 11:01 UTC, tabman83 commented on src/CaptainHook.DirectorService/DirectorService.cs
> +
Can you explain this change?

2020-09-04 11:11 UTC, nikhilgirraj commented on src/CaptainHook.DirectorService/DirectorService.cs
> +
The unit tests were written wrong which led me to believe that Deletion can result in a .None or a .Success result. but it is changed now, as @dawidkeshop explained, Deletion in ServiceFabric results in a .None but we return .Sucess to reflect successful delete event.

2020-09-04 12:00 UTC, nikhilgirraj commented on src/CaptainHook.DirectorService/DirectorService.cs
> +                await DeleteSubscriptionAsync(readerChange, _cancellationToken);
Made changes with Dawid on call.

2020-09-04 13:33 UTC, dawidkeshop approved these changes

2020-09-04 13:47 UTC, merged