#84938 Update SubscriberEntityToConfiguration mapper to support callb…
eShopWorld/captain-hook pull request #261
Opened 2020-09-13 21:44 UTC by tabman83

…acks

2020-09-14 09:06 UTC, tabman83 commented
Still in draft state because I want to add few tests.

2020-09-14 22:00 UTC, chomick requested changes
we should not be duplicating mapping code. also, for dlq, we will need more then one subscriber config, right?

2020-09-15 07:13 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/Mappers/ISubscriberEntityToConfigurationMapper.cs
> -        Task<OperationResult<IEnumerable<SubscriberConfiguration>>> MapSubscriberAsync(SubscriberEntity entity);
I think you're right, I will re-look at that

2020-09-15 07:13 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +                entity.Webhooks?.Endpoints?.Count() == 1 &&
I'll double check what I can do there

2020-09-15 09:10 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/Mappers/ISubscriberEntityToConfigurationMapper.cs
> -        Task<OperationResult<IEnumerable<SubscriberConfiguration>>> MapSubscriberAsync(SubscriberEntity entity);
This has been changed.

2020-09-15 12:28 UTC, tabman83 commented
I will be adding tests with a subsequent PR

2020-09-15 13:16 UTC, dawidkeshop approved these changes

2020-09-16 09:31 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<IEnumerable<SubscriberEntity>>> CreateReaderAsync(SubscriberEntity subscriber)
Why do we return list of subscriber entities and passing a single entity as input?

2020-09-16 09:32 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<IEnumerable<SubscriberEntity>>> CreateReaderAsync(SubscriberEntity subscriber)
Did you mean to return subscriber configs (KV models?)

2020-09-16 09:50 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/DirectorService/IDirectorServiceProxy.cs
> +        /// A IEnumerable<SubscriberConfiguration> if update has been invoked
Even here is the right type listed :) I think it doesn't make sense to return multiple entities (there will always be just one - the same as you passed as an input) but it does to return many configs as DLQ may be another one

2020-09-16 09:58 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +            subscriberConfiguration.SubscriberName = entity.Name;
Do we give any special name to callbacks?
Currently, in configs, we assign the name with "-callback" suffix. Is that used in anyway or can we safely ignore that?

2020-09-16 10:00 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +            subscriberConfiguration.SubscriberName = entity.Name;
Also, is it safe not to create "webhookConfig" level and have only "subscribers" list in the KV models?

2020-09-16 10:10 UTC, chomick commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +        public static SubscriberConfiguration FromWebhookConfig(WebhookConfig webhookConfig)
You are duplicating the logic - can you use this method inside the other one so those mappings are implemented

2020-09-16 10:12 UTC, chomick commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +                HttpVerb = webhookConfig.HttpVerb,
Which one do we use: verb or method?

2020-09-16 10:12 UTC, chomick commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +        public static SubscriberConfiguration FromWebhookConfig(WebhookConfig webhookConfig)
And you missed a few fields to map

2020-09-16 10:14 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +            subscriberConfiguration.SubscriberName = entity.Name;
Ignore - I thought we are mapping this in a different way - all good.

2020-09-16 10:18 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +                Name = subscriberEntity.Id,
So this will be a duplicate now? Callbacks and webhooks will have the same name?
Maybe we should only pass what is needed in the mappings, i.e.:
- webhook entity
- its name (string)
- event type (string)

2020-09-16 10:19 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +        private async Task<OperationResult<WebhookConfig>> MapWebhooksAsync(SubscriberEntity subscriberEntity, WebhooksEntity webhooksEntity)
We do not need entire subscriber entity here, you just need a webhook, the name you want to give to the webhook and event type

2020-09-16 10:22 UTC, chomick commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +        public static SubscriberConfiguration FromWebhookConfig(WebhookConfig webhookConfig)
Do you have unit tests for that?

2020-09-16 10:23 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<IEnumerable<SubscriberEntity>>> CreateReaderAsync(SubscriberEntity subscriber)
Do you have unit tests verifying now that callbacks are properly passed in?

2020-09-16 10:26 UTC, chomick requested changes
Few concerns:
- return types (list of entity vs config)
- possibly missing unit tests (ok if you plan to do it in subsequent PRs)
- possibly incorrect mappings to subscriber config

2020-09-16 12:08 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/DirectorService/IDirectorServiceProxy.cs
> +        /// A IEnumerable<SubscriberConfiguration> if update has been invoked
Changed

2020-09-16 13:23 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<IEnumerable<SubscriberEntity>>> CreateReaderAsync(SubscriberEntity subscriber)
Changed

2020-09-16 13:25 UTC, tabman83 commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +                HttpVerb = webhookConfig.HttpVerb,
verb - method is gathered from verb

2020-09-16 13:37 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +            subscriberConfiguration.SubscriberName = entity.Name;
there is no subscriber for callback. the SB subscription is created only for webhooks and dlq

2020-09-16 13:40 UTC, tabman83 commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +        public static SubscriberConfiguration FromWebhookConfig(WebhookConfig webhookConfig)
I have used this method inside the other one

2020-09-16 14:14 UTC, tabman83 commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +        public static SubscriberConfiguration FromWebhookConfig(WebhookConfig webhookConfig)
Added

2020-09-16 14:15 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<IEnumerable<SubscriberEntity>>> CreateReaderAsync(SubscriberEntity subscriber)
The mapper is thoroughly tested!

2020-09-16 14:28 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +            subscriberConfiguration.SubscriberName = entity.Name;
ok, so I understand the webhook name (in callback) is not used in any way.

2020-09-16 14:31 UTC, chomick commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +        public static SubscriberConfiguration FromWebhookConfig(WebhookConfig webhookConfig)
ok, maybe we are not passing them just now (yet) but when you map from webhook config to subscriber, I would expect to have _all_ fields mapped, even if you think some of them may not be set right now.
It will save you a bug next time when timeout gets introduced to DTO and you will wonder why it is not mapped? :)

2020-09-16 14:33 UTC, tabman83 commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +        public static SubscriberConfiguration FromWebhookConfig(WebhookConfig webhookConfig)
I see your point I will change that!

2020-09-16 14:34 UTC, chomick commented on src/CaptainHook.Common/Configuration/EventHandlerConfig.cs
> +                HttpVerb = webhookConfig.HttpVerb,
Is one of them a calculated property? Maybe we can make one of them readonly to avoid mistakes? Does not need to be part of this PR but if quick, maybe worth doing...
If we use Verb as an input, maybe Method should be only a calculated property.

2020-09-16 14:35 UTC, chomick commented on src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DeleteSubscriberRequestHandlerTests.cs
> +                .ReturnsAsync(new List<SubscriberConfiguration>());
You know you cna also return Enumerable.Empty<..> - cleaner intentions and better for GC :)

2020-09-16 14:36 UTC, chomick commented on src/Tests/CaptainHook.Application.Tests/Infrastructure/DirectorServiceProxyTests.cs
> +            result.Data.Should().NotBeNullOrEmpty();
This could have been like it before but do we have any test that verifies the actual output of the method as well?

2020-09-16 14:36 UTC, chomick approved these changes

2020-09-16 14:37 UTC, tabman83 commented on src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DeleteSubscriberRequestHandlerTests.cs
> +                .ReturnsAsync(new List<SubscriberConfiguration>());
I actually tried that and it wouldn't compile!

2020-09-16 14:39 UTC, tabman83 commented on src/Tests/CaptainHook.Application.Tests/Infrastructure/DirectorServiceProxyTests.cs
> +            result.Data.Should().NotBeNullOrEmpty();
I will have it as a separate PR as that result is not being used

2020-09-16 14:58 UTC, merged