DTO and validator updated for DLQ
eShopWorld/captain-hook pull request #262
Opened 2020-09-14 16:09 UTC by dawidkeshop

2020-09-15 08:12 UTC, tabman83 requested changes

2020-09-15 08:12 UTC, tabman83 commented on src/CaptainHook.Application/Validators/Dtos/SubscriberDtoValidator.cs
> +                .SetValidator(new WebhooksDtoValidator("Callbacks"));
I'd say DLQ here

2020-09-15 08:20 UTC, dawidkeshop commented on src/CaptainHook.Application/Validators/Dtos/SubscriberDtoValidator.cs
> +                .SetValidator(new WebhooksDtoValidator("Callbacks"));
sure

2020-09-15 11:17 UTC, tabman83 reviewed
May I suggest we call them DlqHooks to reinforce the concept they are still webhooks, just fired when an event ends up in DLQ? @chomick @dawidkeshop @mszymeshop @nikhilgirraj

2020-09-17 08:55 UTC, tabman83 commented on src/CaptainHook.Application/Validators/Dtos/SubscriberDtoValidator.cs
>          }
Shouldnt this be DlqHooks as well?

2020-09-17 08:58 UTC, tabman83 approved these changes

2020-09-17 10:42 UTC, dawidkeshop commented on src/CaptainHook.Application/Validators/Dtos/SubscriberDtoValidator.cs
>          }
Of course it should, by mistake I just didn't save all changes in this file.

2020-09-17 11:19 UTC, merged