85193 mapping DLQ data to send it to DirectorService
eShopWorld/captain-hook pull request #280
Opened 2020-09-21 16:41 UTC by dawidkeshop

2020-09-24 14:06 UTC, chomick requested changes

2020-09-24 14:06 UTC, chomick commented on src/CaptainHook.Application/Handlers/Subscribers/DirectorServiceChanger.cs
> +    public class DirectorServiceChanger : IDirectorServiceChanger
I think we lost the way somewhere :) this is not what we discussed

2020-09-24 14:06 UTC, chomick commented on src/CaptainHook.Application/Handlers/Subscribers/DirectorServiceChanger.cs
> +    public class DirectorServiceChanger : IDirectorServiceChanger
This class should only determine what changes are to be applied but it should not be applying them.
Instead, it was supposed to return the list of operations to be executed by handler on director service.

2020-09-24 15:01 UTC, dawidkeshop commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<SubscriberConfiguration>> CreateReaderAsync(SubscriberEntity subscriber)
This proxy is a border between API and `DirectorService.ApplyReaderChange` - other classes don't have to know the DirectorService contract, don't have to map to KV models and can operate only on entities. If something changes in DirectorService, we will have to update this class only.
If we make proxy to accept list of operations, it means that handlers and other classes will have to deal with KV models. It's potentially more places to update in case of any change.

Moreover, methods from proxy are used by many handlers. Should all these flows be replaced with the new approach?

2020-09-24 15:49 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<SubscriberConfiguration>> CreateReaderAsync(SubscriberEntity subscriber)
But you are still leaking the SubscriberConfiguration out of the proxy (return values). Also, by design, the other class we were meant to create was also responsible knowing how to convert and interpret the entity class into KV config classes.

Right now, there is a false impression that we can deal with Entities only talking to Director but this is not correct - you still need to create separate calls to Director as Readers/KV models are not 100% compatible with entity models.

Also, in relation to other usages - why not use a single interaction point with the director in a coherent way? You define the operations and you pass them to the director.

2020-09-24 15:51 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<SubscriberConfiguration>> DeleteDlqReaderAsync(SubscriberEntity subscriber)
Here, you still leak the fact that DLQ from an entity cannot be processed with a normal call - I think this looks like a Francenstain a bit :)

2020-09-24 16:42 UTC, mszymeshop commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +                throw new ArgumentException("Entity must contain Dlqhooks", nameof(entity));
nit: nameof(PROPERTY)?

2020-09-24 16:42 UTC, mszymeshop commented on src/CaptainHook.Application/Handlers/Subscribers/DirectorServiceChanger.cs
> +    public class DirectorServiceChanger : IDirectorServiceChanger
Such an approach would simplify the tests as well as they base on interactions at the moment and really should base on data. The application of the change-request is then a small subset of what you need to test.

2020-09-25 09:27 UTC, chomick commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<SubscriberConfiguration>> DeleteReaderAsync(SubscriberEntity subscriber)
I suggest we mark those methods as Obsolete/legacy in some way so they are no longer used as the preferred way of usage will be via CallDirectorService.

2020-09-25 09:43 UTC, dawidkeshop commented on src/CaptainHook.Application.Infrastructure/Mappers/SubscriberEntityToConfigurationMapper.cs
> +                throw new ArgumentException("Entity must contain Dlqhooks", nameof(entity));
But which property?

2020-09-25 10:02 UTC, chomick commented on src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DirectorServiceRequestsGeneratorTests.cs
> +            array[0].Should().BeOfType<UpdateReader>();
Would be good to verify at least the names of the subscribers?

2020-09-25 10:03 UTC, chomick commented on src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DirectorServiceRequestsGeneratorTests.cs
> +        public async Task When_NewSubscriberWithDlq_ThenWebhookAndDlqReadersCreated()
Can you add also tests for updating subscriber webhooks without DLQ?

2020-09-25 10:03 UTC, chomick approved these changes

2020-09-25 10:05 UTC, dawidkeshop commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
> +        public async Task<OperationResult<SubscriberConfiguration>> DeleteReaderAsync(SubscriberEntity subscriber)
Sure

2020-09-25 11:16 UTC, dawidkeshop commented on src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DirectorServiceRequestsGeneratorTests.cs
> +            array[0].Should().BeOfType<UpdateReader>();
Sure

2020-09-25 11:29 UTC, dawidkeshop commented on src/Tests/CaptainHook.Application.Tests/Handlers/Subscribers/DirectorServiceRequestsGeneratorTests.cs
> +        public async Task When_NewSubscriberWithDlq_ThenWebhookAndDlqReadersCreated()
Good catch!

2020-09-25 11:46 UTC, merged