87176 DirectorServiceProxy cleanup
eShopWorld/captain-hook pull request #304
Opened 2020-09-28 17:24 UTC by dawidkeshop

2020-09-28 17:25 UTC, tabman83 requested changes

2020-09-28 17:25 UTC, tabman83 commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
>          public async Task<OperationResult<SubscriberConfiguration>> CallDirectorService(ReaderChangeBase request)
-Async suffix

2020-09-29 07:40 UTC, chomick commented on src/CaptainHook.Application/Handlers/Subscribers/DeleteWebhookRequestHandler.cs
> +            return await existingItem.Data.RemoveWebhookEndpoint(EndpointEntity.FromSelector(request.Selector))
Nice and neat

2020-09-29 07:42 UTC, chomick approved these changes

2020-09-29 07:53 UTC, dawidkeshop commented on src/CaptainHook.Application.Infrastructure/DirectorService/DirectorServiceProxy.cs
>          public async Task<OperationResult<SubscriberConfiguration>> CallDirectorService(ReaderChangeBase request)
Fixed

2020-09-29 08:13 UTC, tabman83 approved these changes

2020-09-29 08:15 UTC, merged