Added method to parse variables from the JSON file.
eShopWorld/captain-hook pull request #311
Opened 2020-09-30 15:02 UTC by nikhilgirraj

Intended flow of parsing -
1. Parse Vars as Dict
2. Replace vars in content string 
3. Replace params in content string
4. Parse Content string as PutSubscriberRequest as before
5. Profit?

2020-09-30 15:51 UTC, dawidkeshop reviewed
Couple naming suggestions. Maybe not crucial, but in couple weeks or months will help us to understand what and why is happening in the code.

2020-09-30 15:51 UTC, dawidkeshop commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +using JetBrains.Annotations;
What's that? `JetBrains.Annotations` sounds like something very internal, non-standard and something which can't be trusted. :)

2020-09-30 15:51 UTC, dawidkeshop commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                foreach (var (key1, innerDict) in varsDictionary)
I would use a name which is more descriptive than `key1`. Like `propertyKey` maybe?

2020-09-30 15:51 UTC, dawidkeshop commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                    foreach (var (key2, val) in innerDict)
I would use a name which is more descriptive than `key2`. Like `environmentsKey` maybe?
And `envsValues` or `valuesForEnv` than `innerDict`?

I mean to use a name which tells the purpose not the internal file location.

2020-09-30 15:51 UTC, dawidkeshop commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                            foreach (var key in key2.Split(','))
`singleEnv` instead of `key`?

2020-09-30 15:51 UTC, dawidkeshop commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                            outputVarsDictionary[key1][key2] = val.Type == JTokenType.String ? val.ToString() : val.ToString(Formatting.None);
Why this logic is different than in the previous `if` statement?
I think we can have a `string` and `node` regardless if this is set for one or several environments.

2020-09-30 15:59 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +using JetBrains.Annotations;
Yes, I was trying something and ended up not using this namespace. This should have been automatically removed. :/

2020-09-30 16:00 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                foreach (var (key1, innerDict) in varsDictionary)
Wanted to use something that would say key at level 1 and key at level 2. Later understood that the second level is always env. Will change it now.

2020-09-30 16:19 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                        var stringVal = val.Type == JTokenType.String ? val.ToString() : val.ToString(Formatting.None);
I would not make this distinction - why not always toString (none)?

2020-09-30 16:20 UTC, dawidkeshop commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +using JetBrains.Annotations;
`ctrl + R, ctrl + G` is a friend. ;)

2020-09-30 16:20 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                                outputVarsDict[propertyKey][singleEnv] = stringVal;
Just be sure to:
- trim spaces
- check for empty env names

2020-09-30 16:20 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                foreach (var (propertyKey, innerDict) in varsDict)
proeprtyKey == variableName?

2020-09-30 16:23 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +            if (fileContent.ContainsKey("vars"))
See if you can break down this method - it got rather complex

2020-09-30 16:36 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                var request = JsonConvert.DeserializeObject<PutSubscriberRequest>(contentJObject.ToString());
Are you planning to run the vars substitution here or later?
You may want to think how the substitution would work - that may help you with the definition of what data structures you actually will need to hold the vars in.

Because we are expecting correct Json as an input, we have to push the variable name into a string in our Json request definition. That means you can't simply apply string-replace for the variables as you would also have to remove the string literals from the output.

That leaves you with only one option: iterate over all elements in your JObject (recursively) and if any node has a string value, apply vars replacement in that string (that would be nice, little service you could have: input is a string & vars dictionary and output is converted string or value/JToken). 
The result would have to be attached to the node instead original string. 

Here is a second problem: you will need to differentiate between simple string replacement vs substituting string variable usage with complex object the variable represents.

We wanted to be able to support entries like:

```
  "vars": { "name" : "random string" }

  ...
  "some-property": "regular string {var:name} with variable inside",
  ...
```

but also this:

```
  "vars": { "name" : { "complex": "object"}  }

  ...
  "some-property": "{var:name}",
  ...
```
So when you attempt to substitute the variable name with a value, there must be some logic applied that will detect what is the value you try to inject and whether it is a valid substitution in a given context. For the case below, the usage of variable below would be incorrect:

```
  "vars": { "name" : { "complex": "object"}  }

  ...
  "some-property": "my string here and {var:name}", // we can't really do that - complex object can be substituted only when the variable is used on its own
  ...
```

Also, on top of all that, you will have parameters substitution on the variables and other content as well :)

2020-09-30 16:39 UTC, chomick commented on src/Tests/Platform.Eda.Cli.Tests/Commands/ConfigureEda/SubscribersDirectoryProcessorTests.cs
> +        public void ProcessDirectory_JsonFileWithVars_ReturnsValidObject()
You definitively want to break this functionality out into some service/class.
As you start adding more logic, testing this will be impossible.

2020-10-01 07:34 UTC, tabman83 requested changes
I think that if you look at the set of operations needed to perform an event configuration you can define a pipeline of stages:
1. read the file and parse the json
2. replace params
3. replace variables
4 call the API

Right now everything is done in one single place for all files at the same time. If you were to change your code in a way where you have different services, and each service only takes care of one stage per one file, then you could have your pipeline in place. Once this is achieved you would ideally process one file at a time (thus having a single log as requested by @chomick ) - but since the pipeline can be asynchronous as soon as one file moves to the second stage you can start processing another one.

I don't expect all the stages to take a similar amount of time so this won't be an extreme parallelization.

Hope I was clear.

2020-10-01 07:34 UTC, tabman83 commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                var request = JsonConvert.DeserializeObject<PutSubscriberRequest>(contentJObject.ToString());
I suggest you have separate services for
- variables substitution
- parameters substitution
This way the entire code is more testable (you can test the different substitution services in isolation)

Also I'd suggest you use JSONPath to retrieve the variables and parameters

2020-10-01 08:09 UTC, dawidkeshop commented on src/Platform.Eda.Cli/Commands/ConfigureEda/SubscribersDirectoryProcessor.cs
> +                var request = JsonConvert.DeserializeObject<PutSubscriberRequest>(contentJObject.ToString());
This task is only about reading vars from JSON file, variables and parameters substitutions have separated, follow-up tasks.

2020-10-02 08:33 UTC, tabman83 commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/SubscriberFileParser.cs
> +            {
If this is going to be part of a separate service (step) then you can remove it from here.

2020-10-02 08:33 UTC, tabman83 commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/SubscribersDirectoryProcessor.cs
>          public OperationResult<IEnumerable<PutSubscriberFile>> ProcessDirectory(string inputFolderPath)
This is currently returning an empty collection of PutSubscriberFile. Is it just a stub?

2020-10-02 08:56 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/SubscriberFileParser.cs
> +            {
Just noticed. Removing it.

2020-10-02 12:29 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/SubscribersDirectoryProcessor.cs
>          public OperationResult<IEnumerable<PutSubscriberFile>> ProcessDirectory(string inputFolderPath)
It is a stub for now. The next task is to chain all the components together. As part of that - 
1. This one (SubscriberDirectoryProcessor) will be changed to return a IEnumerable<string> list of files instead.
2. Control code will be moved to a new class (that chains all steps) from [ConfigureEdaCommand](https://github.com/eShopWorld/captain-hook/blob/5359812b7d8c0d74429ced3c30046414aeaefc87/src/Platform.Eda.Cli/Commands/ConfigureEda/ConfigureEdaCommand.cs)

2020-10-02 12:58 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/IJsonVarsParser.cs
> +        public Dictionary<string, JToken> GetFileVars(JObject fileContent, string environmentName);
Can you add comments/documentation for the interface/method, please?
We need to start doing this for all public interfaces

2020-10-02 12:59 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsParser.cs
> +                        foreach (var singleEnv in envKey.Split(','))
Trim spaces and check for empty env name?
Also, should we have a list of valid env's or do we accept any string here?

2020-10-02 13:00 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsParser.cs
> +            fileContent.Remove("vars");
Are we happy with this side-effect? Will it be clear for the consumer of the interface that this will happen?

2020-10-02 13:02 UTC, chomick approved these changes

2020-10-02 13:57 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsParser.cs
> +            fileContent.Remove("vars");
Maybe renaming the method / interface to extract vars would be more appropriate?

2020-10-02 13:58 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/IJsonVarsParser.cs
> +        public Dictionary<string, JToken> GetFileVars(JObject fileContent, string environmentName);
Yes, I was doing that earlier but I don't know why I stopped. :/

2020-10-02 15:25 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsParser.cs
> +                        foreach (var singleEnv in envKey.Split(','))
Would it be better to check against a finite list of valid env names?

2020-10-02 17:49 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsParser.cs
> +                        foreach (var singleEnv in envKey.Split(','))
I think we should have a list of valid names - that may be used in many places, actually, so should be shared.

2020-10-02 17:50 UTC, chomick commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsParser.cs
> +            fileContent.Remove("vars");
I just wonder why we have to modify the input? You can always, outside of this class, extract the subscriber section and use it for further processing - no need to do it here.

2020-10-02 18:20 UTC, tabman83 approved these changes

2020-10-04 17:04 UTC, tabman83 requested changes

2020-10-04 17:04 UTC, tabman83 commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsParser.cs
> +            foreach (var (propertyKey, innerDict) in varsDict)
If this (or the rest of the process) breaks for any reason it will blow up. I would leverage OperationResult to report back the error.

2020-10-05 14:48 UTC, tabman83 requested changes

2020-10-05 14:48 UTC, tabman83 commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsExtractor.cs
> +            if (varsDict == null)
If this section does not fit into your model it will blow up. You should catch it and leverage OperationResult to return it.

2020-10-05 16:07 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsExtractor.cs
> +            if (varsDict == null)
oh, now I understand. I did not get it the last time.

2020-10-05 16:15 UTC, nikhilgirraj commented on src/Platform.Eda.Cli/Commands/ConfigureEda/JsonProcessor/JsonVarsExtractor.cs
> +            if (varsDict == null)
Fixed

2020-10-05 16:17 UTC, tabman83 approved these changes

2020-10-05 16:28 UTC, merged