92430 stop loading subscribers from KV
eShopWorld/captain-hook pull request #379
Opened 2020-11-06 09:00 UTC by dawidkeshop

2020-11-06 09:13 UTC, tabman83 requested changes

2020-11-06 09:13 UTC, tabman83 commented on src/CaptainHook.DirectorService/Program.cs
> -                builder.RegisterType<ConfigurationMerger>()
There's a SubscribersKeyVaultProvider on line 58 which needs to be removed as well, cannot highlight it from here

2020-11-06 09:15 UTC, tabman83 requested changes

2020-11-06 09:15 UTC, tabman83 commented on src/CaptainHook.DirectorService/Program.cs
> -                builder.RegisterType<ConfigurationMerger>()
Also both ISubscribersKeyVaultProvider.cs and SubscribersKeyVaultProvider.cs needs to be removed

2020-11-06 09:15 UTC, tabman83 commented on src/CaptainHook.DirectorService/Program.cs
> -                builder.RegisterType<ConfigurationMerger>()
And its test files if any

2020-11-06 10:31 UTC, dawidkeshop commented on src/CaptainHook.DirectorService/Program.cs
> -                builder.RegisterType<ConfigurationMerger>()
Good idea! Removed, as well as KeyVaultConfigurationLoader

2020-11-06 10:46 UTC, tabman83 approved these changes
Please hold on to the merge for now

2020-11-06 13:24 UTC, chomick commented on src/CaptainHook.DirectorService/Infrastructure/SubscriberConfigurationLoader.cs
> +                return new MappingError("Cannot map Cosmos DB entries", new ExceptionFailure(ex));
Should you check here which tasks had exceptions and log those?

2020-11-06 18:41 UTC, dawidkeshop commented on src/CaptainHook.DirectorService/Infrastructure/SubscriberConfigurationLoader.cs
> +                return new MappingError("Cannot map Cosmos DB entries", new ExceptionFailure(ex));
I've changed that part, so now we know the ID of failed subscriber entity.
Logging is done by DirectorService.

The question is - do we really should fail DirectorService if one subscriber configuration is broken?

2020-11-09 12:54 UTC, tabman83 commented on src/CaptainHook.DirectorService/Infrastructure/Interfaces/LoadingSubscribersResult.cs
> +        public bool HaveErrors => Errors.Any();
Not meaning to be pedantic, I'd say `HasErrors`

2020-11-09 13:00 UTC, dawidkeshop commented on src/CaptainHook.DirectorService/Infrastructure/Interfaces/LoadingSubscribersResult.cs
> +        public bool HaveErrors => Errors.Any();
Sure, will fix

2020-11-09 17:16 UTC, chomick commented on src/CaptainHook.DirectorService/Infrastructure/Interfaces/LoadingSubscribersResult.cs
> +    public class LoadingSubscribersResult
I didn't think we have to tell the caller what worked what did not? I though we could simply log the individual errors and return correct subscribers?

2020-11-09 17:18 UTC, chomick reviewed
Before we merge this, is there any way to verify (on any env) that there is no longer ANY keyvault config loaded and all of them are already served from DB only?
Do we have some indicator on GET operation on where the config came from?

2020-11-17 09:43 UTC, merged